# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Party Organizer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Party Organizer
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'AERecord'
  pod 'PromiseKit'
  pod 'Kingfisher'
  pod 'Device'
  pod 'KMPlaceholderTextView'
  pod 'SwiftyJSON'
end
